FROM ruby:2.5.7-alpine3.11 AS build

WORKDIR /code

RUN gem install nokogiri  && \
    rm /usr/local/bundle/cache/*.gem

FROM <%= @base_image_tag %>

LABEL org.forwardpmx.os="alpine" \
      org.forwardpmx.os-version="<%= @os_version %>" \
      org.forwardpmx.from.image="<%= @base_image_tag.split(':').first %>" \
      org.forwardpmx.from.tag="<%= @base_image_tag.split(':').last %>" \
      org.forwardpmx.lang.ruby.version="<%= @ruby_version %>"

COPY --from=build /etc/apk/keys/developers@forward3d.com-5a7dfa17.rsa.pub /etc/apk/keys/developers@forward3d.com-5a7dfa17.rsa.pub
COPY --from=build /etc/apk/repositories /etc/apk/repositories

<%= @extra_runtime_packages %>

RUN apk add --no-cache --update openssl-dev && \
    gem install -N bundler -v 2.0.1

WORKDIR /code
COPY . /code
COPY --from=build /usr/local/bundle /usr/local/bundle

<%= @context_steps %>

<%= @post_install_steps %>

<%= @entry_point_or_cmd %>
