FROM ruby:2.5.7-alpine3.11 AS build

RUN apk add --update --no-cache build-base && \
    gem install nokogiri aws-sdk-s3 && \
    rm /usr/local/bundle/cache/*.gem

FROM ruby:2.5.7-alpine3.11

COPY --from=build /usr/local/bundle /usr/local/bundle

WORKDIR /code

COPY main.rb /code/main.rb

CMD ruby main.rb
