FROM golang:1.13-alpine3.11 AS build
RUN apk add --update --no-cache git && \
    go get -u github.com/aws/aws-sdk-go/service/s3
WORKDIR /code
COPY main.go /code/main.go
RUN go build main.go

FROM alpine:3.11
COPY --from=build /code/main main
CMD ./main
